### ISSUE TITLE
If anyone is concerned about the bytes cuz you're a idiot

### ISSUE THREAD

**Issue by TwoThreeTwo** [maywr/NewFagPlugin#1]
It's a pastebin, don't cry about it being a rat. https://pastebin.com/raw/HH23Wurw  <- utf8 byte conversion
Maywr pin this so kids don't cry

**Comment by maywr** [comment]
ye basically that's a bit more secure if link with names for backdoor in bytes

this guy being kinda right

**Comment by maywr** [comment]
but what's the point of making rat in Minecraft plugin with backdoor lol
